### ISSUE TITLE
Getting invalid date error

### ISSUE THREAD

**Issue by mcamayursharma** [regulaforensics/DocumentReader-Android#11]
Unable to initialize the SDK, getting this error - 
License result: {"license":{"status":false,"message":"License step 2 fails: invalid date"}}
The code is correct as it was working fine until yesterday, and suddenly in the live environment, we have started getting the above mentioned error.

**Comment by DmitrySmolyakov** [comment]
Hello @mcamayursharma, your license file has expired, please contact to our manager: zoya.lutsevich@regula.us.
