### ISSUE TITLE
What about localization?

### ISSUE THREAD

**Issue by ildar2** [regulaforensics/DocumentReader-Android#13]
How can we get Status Message and Result Status Message translations?

**Comment by vyakimchik** [comment]
Hi, @ildar2 ! Go to the next page: https://github.com/regulaforensics/DocumentReader-Android/wiki/Localization. There you can find the information where all the strings are located. For example, if you want to change the text "Searching for a document" of the Status, you need to find the `strLookingDocument` string and modify it.
