### ISSUE TITLE
Cannot connect Regula 1120 via mobile device bluetooth

### ISSUE THREAD

**Issue by nAkhmedov** [regulaforensics/DocumentReader-Android#15]
I want to connect Regula 1120 BLE 38 device via bluetooth without success. Could you help me to solve the issue. Thanks in advance.

**Comment by vyakimchik** [comment]
Hello,

What name of the device do you indicate? What application do you use to connect to the Regula 1120 device?

**Comment by nAkhmedov** [comment]
First: i wanted to connect device with mobile device. I saw connecting text on my smartphone without luck.
Second: I want to use this app https://play.google.com/store/apps/details?id=com.regula.documentreader

**Comment by vyakimchik** [comment]
Please, contact us at android.support@regulaforensics.com to get more details about the usage of the device Regula 1120.
