### ISSUE TITLE
Failed to resolve: com.regula.documentreader:api:+aar

### ISSUE THREAD

**Issue by Kostya1375** [regulaforensics/DocumentReader-Android#16]
I placed maven repo in build.gradle(project) file and core dependency in build.gradle(module) file
build.gradle(project) part: 
```
allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "http://maven.regulaforensics.com/RegulaDocumentReader"
        }
    }
}
```
build.gradle(module) part: 
```
dependencies {
    ...
    implementation('com.regula.documentreader:api:+aar') {
        transitive = true
    }
    implementation 'com.regula.documentreader.doctype:core:+@aar'

}
```
I've done all by guide except placing `implementation` part in project file where it's not working

**Comment by vyakimchik** [comment]
Hello. It seems that you incorrectly configured the `build.gradle` file in your project. Please, review our [demo project](https://github.com/regulaforensics/DocumentReader-Android/tree/master/Samples) once again or provide a small demo project where you demonstrate how you implemented our libraries. Thanks!

**Comment by Kostya1375** [comment]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/7387768/77062739-2658c300-69e5-11ea-8eca-c24083d13f6e.png">
Thanks! Forgot about checking examples. There is missing '@' in tutorial

**Comment by vyakimchik** [comment]
The page has been updated. Thanks for indicating it!
