### ISSUE TITLE
db.dat read error

### ISSUE THREAD

**Issue by KuanyshLes** [regulaforensics/DocumentReader-Android#20]
Getting this error when initialize, says"db.dat is incorrect"

**Comment by vyakimchik** [comment]
Hi. It seems that you updated the SDK, but didn't update the database. What API and Core versions do you use?

**Comment by vyakimchik** [comment]
There hasn't been any activity on this issue recently. Therefore, this issue will be closed. Feel free to open a new one if you still experience this problem.
