### ISSUE TITLE
Am using DocumentReader sdk 

### ISSUE THREAD

**Issue by Diandson** [regulaforensics/DocumentReader-Android#21]
I use that sdk for a week but today a got an error.

private DocumentReader.DocumentReaderCompletion completion = new DocumentReader.DocumentReaderCompletion() {
                          ^
  symbol:   class DocumentReaderCompletion

**Comment by vyakimchik** [comment]
Hello. See the following issue: #19.

**Comment by Diandson** [comment]
Hi
Sorry for late, i got this error this morning I try many to fix it in vein
cause I created the issue hope someone help.

**Comment by vyakimchik** [comment]
`DocumentReader.DocumentReaderCompletion` was changed to `IDocumentReaderCompletion`.

The migration guide from v5.0 to v5.1 can be found here: https://docs.regulaforensics.com/android/migration-guide#completion.

**Comment by Diandson** [comment]
Ok I go try it

**Comment by Diandson** [comment]
Seen about my error. I apply the migration settings but also the same thing


Le ven. 12 juin 2020 à 08:16, Mustapha Dianda <mdianda.md@gmail.com> a
écrit :

> Ok I go try it
>
>
> Le ven. 12 juin 2020 à 07:01, Vladislav Yakimchik <

**Comment by vyakimchik** [comment]
Do you have the following import in your project: `import com.regula.documentreader.api.completions.IDocumentReaderCompletion;` ?

**Comment by Diandson** [comment]
Hi
I fixed it!

**Comment by vyakimchik** [comment]
Great!
