### ISSUE TITLE
IDocumentReaderCompletion.onCompleted does not get called in Fragment

### ISSUE THREAD

**Issue by mariuspena** [regulaforensics/DocumentReader-Android#22]
Scenario: 

I want to read the MRZ from an ID Card. Made a fragment and called showScanner with the appropriate IDocumentReaderCompletion listener. The onCompleted does not get called.

If I do the same in an activity, the onCompleted works.

**Comment by vyakimchik** [comment]
Hello. Could you please provide a small demo project where this issue can be reproduced and send it to support@regulaforensics.com? (you can modify ours which is available in this repo)

**Comment by vyakimchik** [comment]
I'll close the issue for now due to inactivity. Feel free to reopen if the issue isn't solved.
