### ISSUE TITLE
Access the camera image stream

### ISSUE THREAD

**Issue by ivangr1** [regulaforensics/DocumentReader-Android#23]
Hello!

I am using your SDK for a while now and it works great.
I would like to develop a custom feature in my app which needs access to the camera video stream while it is being processed, preferably as a `ByteArray`, or just one frame that was used to recognize would be enough, but I don't see any method with which I could do that.
I can see that you had that option in your older SDK which was deprecated:
https://github.com/regulaforensics/RegulaDocumentReader-Android

Would that be possible?

Thank you!

**Comment by vyakimchik** [comment]
Hello. You can find the demo project in the following branch: https://github.com/regulaforensics/DocumentReader-Android/tree/frame-recognition.

**Comment by ivangr1** [comment]
Thank you very much!
