### ISSUE TITLE
Could not resolve com.regula.documentreader.fullrfid

### ISSUE THREAD

**Issue by maxutolen** [regulaforensics/DocumentReader-Android#24]
Hello,
How to use specific version of the library, I tried like this _com.regula.documentreader.fullrfid:core:v5.1_ ?
but it shows _Could not resolve com.regula.documentreader.fullrfid:core:v5.1_
I don't want to use the latest version, like this _implementation 'com.regula.documentreader.fullrfid:core:+@aar'_

**Comment by syakimchik** [comment]
If you want to set up a specific version, first of all, you need to find out it [here](https://maven.regulaforensics.com/RegulaDocumentReader/com/regula/documentreader/fullrfid/core/)
After that, write selected version instead of '+' like:
`com.regula.documentreader.fullrfid:core:5.1.3032@aar`

**Comment by vyakimchik** [comment]
I'll close the issue for now due to inactivity. Feel free to reopen if the issue isn't solved.
