### ISSUE TITLE
Javadoc is too old

### ISSUE THREAD

**Issue by bomiyr** [regulaforensics/DocumentReader-Android#27]
Javadoc in 'docs' directory is 3 years old and I did not find more recent version online on https://docs.regulaforensics.com/android/. 
For example, DocumentReader.prepareDatabase() and DocumentReader.runAutoUpdate() are missing. 
Online documentation is good, but do you have anything more specific, with description for classes/methods/fields etc. (similar to javadoc)?

**Comment by vyakimchik** [comment]
Hello,

All documentation is available here: https://docs.regulaforensics.com/android. It is being kept up to date. Here is the description of what `prepareDatabase` and `runAutoUpdate` do: https://docs.regulaforensics.com/android/database.
