### ISSUE TITLE
Result message with key strKeepDeviceStill not translated

### ISSUE THREAD

**Issue by janaoravcova** [regulaforensics/DocumentReader-Android#29]
I have translations for messages present in strings.xml file and all of them get used except the message Hold the device still with the key strKeepDeviceStill. That one is used in the original form, not my translation. I located the original values.xml and the key did not seem to change. Where is the problem then?
Thank you!

**Comment by vyakimchik** [comment]
Hello,

Sorry for keeping you waiting and thanks for reporting! We've taken a look at what you mentioned, and it seems that it's a bug. We'll keep you posted once we resolve it.

Thanks!

**Comment by vyakimchik** [comment]
Hello,

The issue has been fixed in v5.5. Feel free to reopen it if you still experiencing the same behavior.
