### ISSUE TITLE
Missing SSL on your Maven repository

### ISSUE THREAD

**Issue by simez** [regulaforensics/DocumentReader-Android#3]
I've noticed your Maven repository is not accessible over SSL. After some investigation, it looks like you have an invalid certificate configured on the domain. You have a wildcard subdomain certificate, so adding it to the maven repository should be a straightforward process.

I have security concerns about loading packages from non-secure URLs, please address this if possible.

**Comment by ikliashchou** [comment]
Fixed. Thanks for pointing this out.
