### ISSUE TITLE
 Could not resolve com.regula.documentreader.fullrfid:core:5.4.+

### ISSUE THREAD

**Issue by chinaltz** [regulaforensics/DocumentReader-Android#30]
Unknown host 'maven.regulaforensics.com'. You may need to adjust the proxy settings in Gradle.

**Comment by vyakimchik** [comment]
Hello,

We've checked, it's available. Do you encounter this error when trying to build our demo project that is available in this repository?

**Comment by vyakimchik** [comment]
Hello,

Have you managed to solve the issue?

**Comment by vyakimchik** [comment]
@chinaltz,

I close this issue due to inactivity for a long time. If you are still experiencing this issue, feel free to reopen it or create a new one.

Thanks!
