### ISSUE TITLE
Manifest merger failed error

### ISSUE THREAD

**Issue by jonneymendoza** [regulaforensics/DocumentReader-Android#34]
HI, i am trying to add regular to our existing  kotlin android app that uses dynamic feature modules and i am receiving this error below everytime i add the dependencies for this sdk.:

```
Task :app:processDebugMainManifest FAILED


/home/me/app/src/main/AndroidManifest.xml:24:18-86 Error:
	Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.5.0] AndroidManifest.xml:24:18-86
	is also present at [:features:myFeature] AndroidManifest.xml:50:9-82 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:9:5-79:19 to override.
```

I tried adding the below as suggested by the error log  below:

`tools:replace="android:appComponentFactory"`

```

/home/me/app/src/main/AndroidManifest.xml:9:5-80:19 Error:
	tools:replace specified at line:9 for attribute android:appComponentFactory, but no new value specified
/home/me/app/src/main/AndroidManifest.xml Error:
	Validation failed, exiting
```

**Comment by DmitrySmolyakov** [comment]
Hello @jonneymendoza! Looks like your project support AndroidX. But our SDK uses Support Libraries dependencies inside. Please, try to add the next option to your gradle.properties file:

android.enableJetifier

More information here: https://developer.android.com/jetpack/androidx

**Comment by jonneymendoza** [comment]
HI @DmitrySmolyakov, thanks for your response.

Do you know if there are any plans to use androidX ?

**Comment by syakimchik** [comment]
Hi @jonneymendoza,
We have migrated our SDK to AndroidX starting from 6.3 version.
