### ISSUE TITLE
Cannot access DocumentReaderException error

### ISSUE THREAD

**Issue by jonneymendoza** [regulaforensics/DocumentReader-Android#35]
Hi, i am trying to handle any potential errors that could occur when preparing the database and initialising the document reader, however i am getting an error stating that DocumentReaderException is not visible for me to use in my code?

I could not identify this object from the docs sections of this project that i downloaded off of here and i am unable to grab the stackflow and message details from DocumentReaderException that is one of the parameters for `  override fun onPrepareCompleted(complete: Boolean, documentReaderError: DocumentReaderException?)`

I did not find any dependencies i needed in order to use this from here https://docs.regulaforensics.com/android/how-to-add-the-sdk-to-the-project 

This is the full error i recieve:

```Cannot access 'com.regula.common.exception.RegulaException' which is a supertype of 'com.regula.documentreader.api.errors.DocumentReaderException'. Check your module classpath for missing or conflicting dependencies```

**Comment by syakimchik** [comment]
Hi @jonneymendoza,
please, make sure you've added implementation API library with  **transitive = true** property correctly.
`implementation ('com.regula.documentreader:api:+@aar'){
    transitive = true
}`

if it's not solved your issue, could you please fork our Sample repository and do the changes you made?
After that, please provide us with it for a detailed investigation.

**Comment by jonneymendoza** [comment]
Brilliant thanks. i forgot to add that. That resolved the isse
