### ISSUE TITLE
Document Reader Exception - No internet

### ISSUE THREAD

**Issue by micocw** [regulaforensics/DocumentReader-Android#38]
Hello,
I have a problem with This SDK as my app - when Initalizing - shows no internet. 
But I am connected to the internet.

Can you please help to solve it?
Or advice how to make it working in offline mode.

Thanks,
M.

**Comment by syakimchik** [comment]
Hello @micocw,
Please, make sure that your manifest contains next permission:

`<uses-permission android:name="android.permission.INTERNET" />`

**Comment by micocw** [comment]
It is there.
I am using the software from github (DocumentReader-Kotlin).
It is strange but it was working ok 2 days ago without any issues.

**Comment by syakimchik** [comment]
hi @micocw,
we have identified the issue. This error returns when your license is expired.
please, contact us at [support@regulaforensics.com](mailto:support@regulaforensics.com)

The description of the error will be fixed in the next release.

**Comment by voprokudin** [comment]
Hi @syakimchik 
I've just created demo license and downloaded `regula.license` file.
When trying to launch your sample `DocumentReader-Kotlin` app the exception appears.
<img width="351" alt="Screenshot 2022-04-28 at 14 44 17" src="https://user-images.githubusercontent.com/47034849/165744944-4ac9df30-2022-4234-b62d-77462a2a866b.png">

**Comment by vyakimchik** [comment]
Hi @micocw, @voprokudin,

Have the issue been solved? Can we close the ticket? If not, could you please try to reproduce the issue on the latest release version that is 7.2? If the issue still happens, please let us know.
