### ISSUE TITLE
Result Status does not always show (strPresentNextPage) -flutter

### ISSUE THREAD

**Issue by anassrasheed** [regulaforensics/DocumentReader-Android#39]
here is my code below 

regula_config : 

void setRegulaConfig(BuildContext context) {
    doc.DocumentReader.setConfig({
      "processParams": {
        "scenario": doc.ScenarioIdentifier.SCENARIO_FULL_PROCESS,
        "returnUncroppedImage": true,
        "multipageProcessing": true,
        "dateFormat": "dd/MM/yyyy",
      },
      "functionality": {"showSkipNextPageButton": true},
      "customization": {
        "resultStatusPositionMultiplier": 0.5,
      }
    });
  }
  
  and here is the code for reading 
  void _regulaEventChannel() {
    setState(() {});
    EventChannel('flutter_document_reader_api/event/completion')
        .receiveBroadcastStream()
        .listen((jsonString) => this.handleCompletion(
            doc.DocumentReaderCompletion.fromJson(json.decode(jsonString))));
  }
  im calling below line after _regulaEventChannel
    doc.DocumentReader.showScanner();

i Also edited the strPresentNextPage in android res/values & res/values-ar to 
    <string name="strPresentNextPage">Scan the other side of the document</string>
    <string name="strPresentNextPage">امسح الوثيقة من الجهة الأخرى </string>
    
    yaml : 
    
   flutter_document_reader_api: ^6.1.0
  flutter_document_reader_core_fullrfid: ^6.1.0

**Comment by vyakimchik** [comment]
Hi @anassrasheed,

Could you please try to reproduce the issue on the latest release version that is 7.2? It seems that the issue was fixed. If not, please let us know.
