### ISSUE TITLE
[FR] Optical Scanning Feature

### ISSUE THREAD

**Issue by phanatagama** [regulaforensics/DocumentReader-Android#49]
We are currently working on a project that requires optical scanning but not for documents. In the Regula SDK the optical scanning feature is only activated automatically when the document is identified on the screen. we would like to ask if there is an alternative way to be able to forcefully activate the optical feature on the camera?

| ![Optical Scanning](https://github.com/regulaforensics/DocumentReader-Android/assets/48324618/72a6e0df-d56f-439d-8c1a-68817dc596e1) | ![optical_scan2](https://github.com/regulaforensics/DocumentReader-Android/assets/48324618/29492cce-c194-4275-9e10-8263c15bee7e) |
| ------------------------------ | ------------------------------ |
| **optical feature active** | **optical feature active** |

**Comment by vyakimchik** [comment]
Hi @phanatagama,

To better assist you with your request, I kindly ask that you write an [email to us](https://support.regulaforensics.com/hc/requests/new). In your email, please provide a detailed description of your business use-case and explain how you plan to utilize the requested feature. This information will help us to better understand your needs and provide the appropriate support.

Please close this issue on GitHub after creating the issue. Thank you!
