### ISSUE TITLE
DocumentReader.Instance().showScanner function has changed

### ISSUE THREAD

**Issue by hasan5151** [regulaforensics/DocumentReader-Android#51]
DocumentReader.Instance().showScanner
before there was 2 params:                 
DocumentReader.Instance().showScanner(requireContext(), completion)
now it is with 3 params:
and i dont know how to use it

Why did u overwrite this function now i cant use it? You could use @Depreciated.

**Comment by hasan5151** [comment]
At least give me dependency with 2 params

**Comment by syakimchik** [comment]
@hasan5151 

It's not a bug. The 'showScanner' method with 2 parameters has already been deprecated in 6.9 version.

Now you need to create object of ScannerConfig class.

https://github.com/regulaforensics/DocumentReader-Android/blob/master/Basic/DocumentReader-sample_kotlin/app/src/main/java/com/regula/documentreader/MainViewModel.kt#L122

`val scannerConfig = ScannerConfig.Builder(Scenario.SCENARIO_FULL_PROCESS).build()
  DocumentReader.Instance().showScanner(context, scannerConfig, completion)`

**Comment by hasan5151** [comment]
results?.getTextFieldValueByType(eVisualFieldType.FT_BANKCARDNUMBER)  return null 
before it was working

**Comment by syakimchik** [comment]
Could you please reproduce the issue on our sample and provide more details what you do?
