### ISSUE TITLE
[EN] Camera frame corner radius gap

### ISSUE THREAD

**Issue by RuiSantosVB** [regulaforensics/DocumentReader-Android#52]
**Bug Description**
There's a gap on the corners between the frame line and the mask whenever you use the Corner camera frame shape.

**Steps To Reproduce**
On the Document Reader with a Custom Camera frame -> Custom shape with the following customizations:
Instance().customization().edit().apply {
    setCameraFrameShapeType(FrameShapeType.CORNER)
    setCameraFrameLineLength(40)
    setCameraFrameCornerRadius(0F)
    setCameraFrameBorderWidth(16)
    apply()
}
The bigger the setCameraFrameBorderWidth is, the more noticeable is the gap. It starts to be noticeable at setCameraFrameBorderWidth(6), on a certain combination of frameborder/cornerradius the gap is reduced and can eventually go away.

**Expected behavior**
Background mask and custom shape should not have gaps in between(?)

**Screenshots**
![gap](https://github.com/regulaforensics/DocumentReader-Android/assets/151060466/bbaaa5f3-ee22-4fff-8591-89db1861b56c)

**Environment:**
 - Device: Samsung Galaxy A32
 - OS version: Android 13

**Comment by vyakimchik** [comment]
Hi @RuiSantosVB,

The issue has been fixed and the new version - 7.3 - has been published. Please update.
