### ISSUE TITLE
[BR] Failed to resolve: com.regula.face:api:+@aar

### ISSUE THREAD

**Issue by komzakdroid** [regulaforensics/DocumentReader-Android#53]
**Bug Description**
Failed to resolve: com.regula.face:api:+@aar

regula_face = "+@aar"

[libraries]
regula-face = { group = "com.regula.face", name = "api", version.ref = "regula_face" }

**Comment by vyakimchik** [comment]
Hi @komzakdroid,

Could you please provide more details about the issue you're experiencing and steps to reproduce on our demo project? Did you follow the [documentation](https://docs.regulaforensics.com/develop/face-sdk/mobile/getting-started/installation/android/#manual-integration)?

**Comment by osamaastal** [comment]
I am facing a similar issue above!

**Comment by osamaastal** [comment]
I am facing a similar issue above! 
note: I have tried also specific versions of sdk (and +@aar ) but the same issue still appeare
more details: 
Could not resolve com.regula.documentreader.core:fullrfid:+.
     Required by:
         project :app
      > Failed to list versions for com.regula.documentreader.core:fullrfid.
         > Unable to load Maven meta-data from http://maven.regulaforensics.com/RegulaDocumentReader/com/regula/documentreader/core/fullrfid/maven-metadata.xml.
            > Could not GET 'https://maven.regulaforensics.comreguladocumentreader/com/regula/documentreader/core/fullrfid/maven-metadata.xml'.
               > maven.regulaforensics.comreguladocumentreader: nodename nor servname provided, or not known
   > Could not resolve com.regula.documentreader:api:+.
     Required by:
         project :app
      > Failed to list versions for com.regula.documentreader:api.
         > Unable to load Maven meta-data from http://maven.regulaforensics.com/RegulaDocumentReader/com/regula/documentreader/api/maven-metadata.xml.
            > Could not GET 'https://maven.regulaforensics.comreguladocumentreader/com/regula/documentreader/api/maven-metadata.xml'.
               > maven.regulaforensics.comreguladocumentreader: nodename nor servname provided, or not known
