### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by YOLA47** [regulaforensics/DocumentReader-Android#56]
https://github.com/regulaforensics/DocumentReader-Android/blob/master/BackendProcessing%2Fapp%2Fsrc%2Fmain%2Fres%2Fdrawable%2Fic_launcher_background.xml

**Comment by vyakimchik** [comment]
Hi @YOLA47,

Could you please provide more details about the issue you're experiencing? This will help us assist you more effectively.
