### ISSUE TITLE
Crash on showAssistAnimation

### ISSUE THREAD

**Issue by garanda21** [regulaforensics/DocumentReader-Android#6]
I'm implementing the SDK on a Samsung Galaxy Tab A (2016) Screen 7" and I receive a crash from method showAssistAnimation on line 1046:

`params.height = (int)CaptureActivity2.this.mCurrentDrawRect.width() / 2;`

When I started the camera on landscape mode, variable **this.mCurrentDrawRect** is `null` 

Android version is 5.1.1

**Comment by mskvorcovs** [comment]
Hello,
This issue is fixed in the latest release 4.0.89599
